// Partituras de ejemplo que se siembran una sola vez por cuenta nueva.
// Son propiedad del usuario (is_demo = true) para que pueda eliminarlas
// individualmente, y no se vuelven a crear mientras la cuenta exista.
export const DEMO_SONGS = [
  {
    title: 'Autumn Leaves',
    artist: 'Joseph Kosma',
    composer: 'Joseph Kosma / Johnny Mercer',
    key: 'Em',
    bpm: 140,
    meter: '4/4',
    type: 'Lead Sheet',
    pages: 1,
    duration: 180,
    is_demo: true,
    file_url: 'https://media.base44.com/images/public/6ab6d2e94e13956919e516f9/40d1a2822_autumnleaves.webp',
    content: [
      'A',
      '[Em]   [Am7]  [D7]    [Gmaj7]',
      '[Cmaj7] [F#m7b5] [B7]  [Em]',
      '',
      'B',
      '[F#m7b5] [B7]  [Em]   [A7]',
      '[Am7]  [D7]    [Gmaj7] [Cmaj7]',
      '[F#m7b5] [B7]  [Em]',
      '',
      'Los pétalos caen, el viento los lleva',
      'El verano ya se fue, el frío nos llega',
      'Tu recuerdo me persigue sin cesar',
      'Como hojas que caen al rodar',
      '',
      'A',
      '[Em]   [Am7]  [D7]    [Gmaj7]',
      '[Cmaj7] [F#m7b5] [B7]  [Em]'
    ].join('\n')
  },
  {
    title: 'All of Me',
    artist: 'Gerald Marks',
    composer: 'Gerald Marks / Seymour Simons',
    key: 'C',
    bpm: 120,
    meter: '4/4',
    type: 'Lead Sheet',
    pages: 1,
    duration: 180,
    is_demo: true,
    file_url: 'https://media.base44.com/images/public/6ab6d2e94e13956919e516f9/ae31420c5_all-of-me.jpg',
    content: [
      'A',
      '[C]      [E7]    [A7]    [Dm]',
      '[E7]     [Am7]   [D7]    [G7]',
      '',
      'B',
      '[C]      [E7]    [A7]    [Dm]',
      '[F]      [F#dim] [C]     [G7]',
      '',
      'Todo mi amor, todo de ti',
      'Tus labios, tu voz, tu mirada',
      'Tomé tu sonrisa y tu melodía',
      'No me dejes, no te vayas jamás',
      '',
      'A',
      '[C]      [E7]    [A7]    [Dm]',
      '[F]      [G7]    [C]'
    ].join('\n')
  },
  {
    title: 'Summertime',
    artist: 'George Gershwin',
    composer: 'George Gershwin / DuBose Heyward',
    key: 'Am',
    bpm: 100,
    meter: '4/4',
    type: 'Lead Sheet',
    pages: 1,
    duration: 180,
    is_demo: true,
    file_url: 'https://media.base44.com/images/public/6ab6d2e94e13956919e516f9/b7b34551f_summertime.png',
    content: [
      'A',
      '[Am]    [Am7]   [D7]    [Fmaj7]',
      '[Am]    [Am7]   [D7]    [Fmaj7]',
      '',
      'B',
      '[Am]    [Am7]   [D7]    [Fmaj7]',
      '[Am]    [E7]    [Am]',
      '',
      'Verano, tu vida es un sueño',
      'El río fluye lento y sereno',
      'No llores pequeño, no tengas temor',
      'El verano vendrá con su canción',
      '',
      'A',
      '[Am]    [Am7]   [D7]    [Fmaj7]',
      '[Am]    [E7]    [Am]'
    ].join('\n')
  },
  {
    title: 'Take Five',
    artist: 'Paul Desmond',
    composer: 'Paul Desmond / Dave Brubeck',
    key: 'Ebm',
    bpm: 180,
    meter: '5/4',
    type: 'Lead Sheet',
    pages: 1,
    duration: 180,
    is_demo: true,
    file_url: 'https://media.base44.com/images/public/6ab6d2e94e13956919e516f9/445843a4b_takefive.webp',
    content: [
      'A',
      '[Ebm]   [Ebm]   [Bbm7]  [Bbm7]',
      '[Ebm]   [Ebm]   [Bbm7]  [Bbm7]',
      '',
      'B',
      '[Abm7]  [Abm7]  [Db7]   [Db7]',
      '[Ebm]   [Ebm]   [Bbm7]  [Bbm7]',
      '',
      'Cinco por cuatro, el compás nos guía',
      'El saxo susurra una melodía',
      'Toma cinco, respira y siente',
      'El jazz que nunca se detiene',
      '',
      'A',
      '[Ebm]   [Ebm]   [Bbm7]  [Bbm7]',
      '[Ebm]   [Ebm]   [Bbm7]  [Bbm7]'
    ].join('\n')
  }
];