import React, { useState, useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Copy, RefreshCw, Users, Music2 } from 'lucide-react';
import { useStage } from '@/components/stage/StageProvider';
export default function Band() {
  const {id}=useParams(),{sets,songs,refresh}=useStage(),setlist=sets.find(s=>s.id===id),[copied,setCopied]=useState(false),[updating,setUpdating]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>refresh().catch(console.error),15000);return()=>clearInterval(timer)},[]);
  const copy=async()=>{await navigator.clipboard.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),2500)};
  if(!setlist)return <p>Repertorio no encontrado. <Link to="/repertorios">Volver</Link></p>;
  return <div className="max-w-3xl space-y-7"><Link to={`/repertorios?abrir=${id}`} className="text-white/55 text-sm flex items-center gap-2"><ArrowLeft size={16}/> Repertorio</Link><div><div className="text-[#c9ef72] text-xs tracking-widest font-bold">TOQUEN EN SINTONÍA</div><h1 className="text-3xl font-bold mt-2">Modo banda</h1><p className="text-white/45 mt-2">Comparte el orden del show con tu banda.</p></div><div className="bg-[#343d35] rounded-3xl p-7"><Users size={30} className="text-[#c9ef72] mb-5"/><h2 className="text-xl font-bold">{setlist.name}</h2><p className="text-white/55 text-sm mt-2">{setlist.song_ids?.length||0} canciones · {setlist.venue||'Lugar por definir'}</p><button onClick={copy} className="mt-6 h-11 px-5 rounded-xl bg-[#c9ef72] text-[#182017] font-bold text-sm flex items-center gap-2"><Copy size={17}/>{copied?'Enlace copiado':'Copiar enlace del repertorio'}</button><p className="text-xs text-white/45 mt-3">Quienes tengan acceso a ScoreBook podrán abrir este repertorio.</p></div><div className="flex justify-between items-center"><h2 className="font-bold">Orden compartido</h2><button disabled={updating} onClick={async()=>{setUpdating(true);try{await refresh()}finally{setUpdating(false)}}} className="text-[#c9ef72] text-sm flex items-center gap-2"><RefreshCw size={15} className={updating?'animate-spin':''}/> Actualizar</button></div><div className="space-y-2">{(setlist.song_ids||[]).map((songId,i)=>{const song=songs.find(s=>s.id===songId);return song&&<div key={songId} className="bg-[#242831] rounded-xl p-4 flex items-center gap-4"><span className="text-white/35">{String(i+1).padStart(2,'0')}</span><Music2 size={17} className="text-[#c9ef72]"/><div><div className="font-semibold">{song.title}</div><div className="text-xs text-white/40">{song.key||'—'} · {song.bpm||'—'} BPM</div></div></div>})}</div></div>;
}