import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {UserRound,Music2,Library,ListMusic,Sun,Moon,ArrowRight} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useStage} from '@/components/stage/StageProvider';
export default function MusicianProfile(){
 const {songs,sets}=useStage(),[user,U]=useState(null),[dark,D]=useState(localStorage.getItem('stage-theme')!=='light');
 useEffect(()=>{base44.auth.me().then(U).catch(console.error)},[]);
 const toggle=()=>{const next=!dark;D(next);localStorage.setItem('stage-theme',next?'dark':'light');document.documentElement.classList.toggle('stage-light',!next)};
 return <div className="max-w-3xl space-y-8"><div><div className="text-[#c9ef72] text-xs tracking-widest font-bold uppercase">TU ESPACIO</div><h1 className="text-3xl sm:text-4xl font-bold mt-2">Perfil</h1></div><div className="rounded-3xl bg-[#242831] p-6 sm:p-8 flex items-center gap-5"><span className="w-16 h-16 rounded-2xl bg-[#c9ef72]/15 flex items-center justify-center text-[#c9ef72]"><UserRound size={30}/></span><div><h2 className="font-bold text-xl">{user?.full_name||'Músico de StageBook'}</h2><p className="text-white/45 text-sm mt-1">{user?.email||'Tu cuenta musical'}</p></div></div><div className="grid grid-cols-2 gap-4">{[[Library,songs.length,'Partituras'],[ListMusic,sets.length,'Repertorios']].map(([Icon,n,label])=><div key={label} className="bg-[#242831] p-6 rounded-2xl"><Icon className="text-[#c9ef72] mb-3" size={22}/><div className="text-3xl font-bold">{n}</div><div className="text-sm text-white/45">{label}</div></div>)}</div><div className="bg-[#242831] rounded-2xl divide-y divide-white/10"><button onClick={toggle} className="w-full flex justify-between items-center p-5 text-sm"><span className="flex items-center gap-3">{dark?<Moon size={18}/>:<Sun size={18}/>} Modo {dark?'oscuro':'claro'}</span><span className="text-white/45">Cambiar</span></button><Link to="/bienvenida" className="flex justify-between items-center p-5 text-sm"><span className="flex items-center gap-3"><Music2 size={18}/> Ver bienvenida</span><ArrowRight size={17} className="text-white/45"/></Link></div><p className="text-xs text-white/35">Tus canciones y repertorios se guardan en tu espacio de StageBook.</p></div>;
}