import React, { useState, useEffect, useRef } from 'react';
import { Link, useParams } from 'react-router-dom';
import { X, ChevronLeft, ChevronRight, StickyNote, Lock, Unlock, Sun, Minus, Plus, Play, Pause, ListMusic } from 'lucide-react';
import ScorePreview from '@/components/stage/ScorePreview';
import NotesPanel from '@/components/stage/NotesPanel';
import { useStage } from '@/components/stage/StageProvider';
export default function Performance() {
  const { id } = useParams();
  const { sets, songs, loading } = useStage();
  const setlist = sets.find(s => s.id === id);
  const ordered = (setlist?.song_ids || []).map(songId => songs.find(s => s.id === songId)).filter(Boolean);
  const [index, setIndex] = useState(0), [page, setPage] = useState(1), [zoom, setZoom] = useState(1), [brightness, setBrightness] = useState(100);
  const [locked, setLocked] = useState(false), [scrolling, setScrolling] = useState(false), [notes, setNotes] = useState(false), [showList, setShowList] = useState(false);
  const scoreRef = useRef(null), touch = useRef(null), wake = useRef(null), song = ordered[index];
  const next = () => { if (!song) return; if (page < (song.pages || 1)) setPage(p => p + 1); else if (index < ordered.length - 1) { setIndex(i => i + 1); setPage(1); } scoreRef.current?.scrollTo({ top: 0 }); };
  const previous = () => { if (page > 1) setPage(p => p - 1); else if (index > 0) { setIndex(i => i - 1); setPage(1); } };
  useEffect(() => { const handler = e => { if (['ArrowRight','PageDown',' ','Enter'].includes(e.key)) { e.preventDefault(); next(); } if (['ArrowLeft','PageUp'].includes(e.key)) { e.preventDefault(); previous(); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [index,page,song]);
  useEffect(() => { let active = true; if (navigator.wakeLock?.request) navigator.wakeLock.request('screen').then(lock => { if (active) wake.current = lock; else lock.release(); }).catch(() => {}); return () => { active = false; wake.current?.release(); wake.current = null; }; }, []);
  useEffect(() => { if (!scrolling) return; const timer = setInterval(() => { if (scoreRef.current) scoreRef.current.scrollTop += 1; }, 70); return () => clearInterval(timer); }, [scrolling]);
  if (loading) return <div className="bg-[#0c0e12] text-white h-screen p-8">Preparando presentación...</div>;
  if (!setlist) return <div className="bg-[#0c0e12] text-white h-screen p-8">Repertorio no encontrado. <Link to="/repertorios">Volver</Link></div>;
  return <div className="h-[100dvh] bg-[#0c0e12] text-white flex flex-col overflow-hidden">
    <header className="flex items-center justify-between px-4 sm:px-6 h-16 shrink-0 border-b border-white/10 gap-3">
      <div className="flex items-center gap-3 min-w-0"><Link to={`/repertorios?abrir=${id}`} aria-label="Salir de presentación" className="p-2 rounded-xl hover:bg-white/10"><X size={21}/></Link><div className="min-w-0"><div className="text-[10px] text-[#c9ef72] uppercase tracking-widest font-bold truncate">{setlist.name} · {index + 1} / {ordered.length}</div><div className="font-semibold text-sm truncate">{song?.title || 'Repertorio vacío'}</div></div></div>
      <div className="flex items-center gap-1"><button onClick={() => setNotes(true)} disabled={!song} aria-label="Notas de interpretación" className="p-2 rounded-xl hover:bg-white/10"><StickyNote size={19}/></button><button onClick={() => setLocked(!locked)} aria-label={locked?'Desbloquear gestos':'Bloquear gestos'} className={`p-2 rounded-xl ${locked?'text-[#c9ef72]':'hover:bg-white/10'}`}>{locked?<Lock size={19}/>:<Unlock size={19}/>}</button><button onClick={() => setShowList(!showList)} aria-label="Lista de canciones" className="p-2 rounded-xl hover:bg-white/10"><ListMusic size={19}/></button></div>
    </header>
    <div className="flex-1 min-h-0 relative bg-[#181a1e]"><div ref={scoreRef} className="h-full w-full overflow-y-auto px-2 sm:px-8 py-3 sm:py-6" onTouchStart={e => touch.current = e.touches[0].clientX} onTouchEnd={e => { if (!locked && touch.current !== null) { const delta = e.changedTouches[0].clientX - touch.current; if (Math.abs(delta) > 70) (delta < 0 ? next : previous)(); touch.current = null; } }}><div className="relative mx-auto max-w-[760px]" style={{filter:`brightness(${brightness}%)`}}><ScorePreview song={song} page={page} zoom={zoom}/></div></div>
      {!locked && song && <><button onClick={previous} aria-label="Página o canción anterior" className="absolute left-0 top-1/3 h-1/3 w-10 sm:w-14 flex items-center justify-center text-white/55 hover:bg-black/20"><ChevronLeft/></button><button onClick={next} aria-label="Página o canción siguiente" className="absolute right-0 top-1/3 h-1/3 w-10 sm:w-14 flex items-center justify-center text-white/55 hover:bg-black/20"><ChevronRight/></button></>}{!song && <div className="absolute inset-0 flex items-center justify-center text-white/50">Agrega canciones a este repertorio antes de comenzar.</div>}
    </div>
    <footer className="shrink-0 border-t border-white/10 px-4 sm:px-6 py-3 flex flex-wrap justify-between items-center gap-3 text-xs sm:text-sm"><div className="flex items-center gap-3"><span className="text-white/55">Página {page} / {song?.pages || 1}</span><span className="hidden sm:inline text-white/55">{song?.key || '—'} · {song?.bpm || '—'} BPM</span></div><div className="flex items-center gap-2"><button onClick={() => setScrolling(!scrolling)} className={`p-2 rounded-lg ${scrolling?'text-[#c9ef72]':'text-white/55'}`} aria-label={scrolling?'Pausar desplazamiento':'Desplazamiento automático'}>{scrolling?<Pause size={18}/>:<Play size={18}/>}</button><Sun size={16} className="text-white/45"/><input type="range" aria-label="Brillo de lectura" min="45" max="130" value={brightness} onChange={e => setBrightness(+e.target.value)} className="w-16 sm:w-24 accent-[#c9ef72]"/><button onClick={() => setZoom(Math.max(.7, +(zoom-.1).toFixed(1)))} aria-label="Reducir zoom" className="p-2"><Minus size={17}/></button><span className="text-white/45 w-8 text-center">{Math.round(zoom*100)}%</span><button onClick={() => setZoom(Math.min(1.6, +(zoom+.1).toFixed(1)))} aria-label="Aumentar zoom" className="p-2"><Plus size={17}/></button></div></footer>
    <div className="h-1 bg-white/10"><div className="h-full bg-[#c9ef72] transition-all" style={{width:`${ordered.length ? (index + page/(song?.pages || 1))/ordered.length*100 : 0}%`}}/></div>
    {notes && song && <NotesPanel song={song} onClose={() => setNotes(false)}/>}
    {showList && <div className="fixed inset-0 z-40 bg-black/70 flex justify-end" onMouseDown={e => e.target===e.currentTarget && setShowList(false)}><div className="bg-[#292d36] w-full max-w-sm p-6 overflow-y-auto"><div className="flex justify-between mb-5"><h2 className="text-xl font-bold">Orden del show</h2><button onClick={() => setShowList(false)} aria-label="Cerrar"><X/></button></div>{ordered.map((s,i) => <button key={s.id} onClick={() => {setIndex(i);setPage(1);setShowList(false)}} className={`w-full text-left p-4 rounded-xl mb-2 ${index===i?'bg-[#c9ef72] text-[#172013]':'bg-white/5'}`}>{i+1}. {s.title}</button>)}</div></div>}
  </div>;
}