import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ChevronLeft, ChevronRight, StickyNote, Pencil, Minus, Plus, Undo2, Redo2 } from 'lucide-react';
import { useStage } from '@/components/stage/StageProvider';
import ScorePreview from '@/components/stage/ScorePreview';
import AnnotationLayer from '@/components/stage/AnnotationLayer';
import NotesPanel from '@/components/stage/NotesPanel';
const tools=[['lapiz','Lápiz'],['resaltador','Resaltador'],['texto','Texto'],['flecha','Flecha'],['forma','Forma'],['borrador','Borrador']];
export default function Viewer() {
  const {id}=useParams(),{songs,loading,saveSong}=useStage();const song=songs.find(s=>s.id===id);
  const [notes,setNotes]=useState(false),[drawing,setDrawing]=useState(false),[tool,setTool]=useState('lapiz'),[page,setPage]=useState(1),[zoom,setZoom]=useState(1),[history,setHistory]=useState(null),[future,setFuture]=useState([]),[color,setColor]=useState('#dc9050');
  const stored=(()=>{try{return JSON.parse(song?.annotations||'[]')}catch{return []}})();const items=history??stored;
  const persist=next=>{setHistory(next);saveSong({annotations:JSON.stringify(next)},id).catch(console.error)};
  const change=next=>{setFuture([]);persist(next)};
  const undo=()=>{if(!items.length)return;setFuture([...future,items.at(-1)]);persist(items.slice(0,-1))};
  const redo=()=>{if(!future.length)return;persist([...items,future.at(-1)]);setFuture(future.slice(0,-1))};
  if(loading)return <p>Cargando partitura...</p>;if(!song)return <p>Partitura no encontrada. <Link to="/biblioteca">Volver a biblioteca</Link></p>;
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/biblioteca" className="flex items-center gap-2 text-sm text-white/55 hover:text-white"><ArrowLeft size={17}/> Biblioteca</Link><div className="flex gap-2"><button onClick={()=>setNotes(true)} className="h-10 px-3 rounded-xl bg-white/10 text-sm flex items-center gap-2"><StickyNote size={16}/> Notas</button><button onClick={()=>setDrawing(!drawing)} className={`h-10 px-3 rounded-xl text-sm flex items-center gap-2 ${drawing?'bg-[#c9ef72] text-[#172013]':'bg-white/10'}`}><Pencil size={16}/> Anotar</button></div></div><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><div className="text-[#c9ef72] uppercase tracking-widest text-xs font-bold">VISOR DE PARTITURAS</div><h1 className="text-2xl font-bold mt-1">{song.title}</h1><p className="text-sm text-white/45 mt-1">{song.artist||'Artista'} · {song.key||'—'} · {song.bpm||'—'} BPM</p></div><div className="flex gap-2 items-center text-sm"><button onClick={()=>setZoom(Math.max(.7,+(zoom-.1).toFixed(1)))} aria-label="Reducir zoom" className="p-2 bg-white/10 rounded-lg"><Minus size={17}/></button><span>{Math.round(zoom*100)} %</span><button onClick={()=>setZoom(Math.min(1.6,+(zoom+.1).toFixed(1)))} aria-label="Aumentar zoom" className="p-2 bg-white/10 rounded-lg"><Plus size={17}/></button></div></div>
    {drawing&&<div className="flex flex-wrap items-center gap-2 bg-[#292d36] rounded-xl p-2">{tools.map(([t,label])=><button key={t} onClick={()=>setTool(t)} className={`px-3 h-9 rounded-lg text-xs font-semibold ${tool===t?'bg-[#c9ef72] text-[#172013]':'text-white/60 hover:bg-white/10'}`}>{label}</button>)}<input type="color" title="Color de anotación" aria-label="Color de anotación" value={color} onChange={e=>setColor(e.target.value)} className="w-8 h-8 bg-transparent ml-auto"/><button title="Deshacer" aria-label="Deshacer" onClick={undo} disabled={!items.length} className="p-2 disabled:opacity-30"><Undo2 size={17}/></button><button title="Rehacer" aria-label="Rehacer" onClick={redo} disabled={!future.length} className="p-2 disabled:opacity-30"><Redo2 size={17}/></button></div>}
    <div className="relative max-w-[760px] mx-auto"><ScorePreview song={song} page={page} zoom={zoom}/><AnnotationLayer items={items.filter(x=>!x.page||x.page===page)} onChange={next=>change([...items.filter(x=>x.page&&x.page!==page),...next.map(x=>({...x,page}))])} tool={tool} color={color} enabled={drawing}/></div><div className="flex justify-center items-center gap-5 pb-8"><button onClick={()=>setPage(Math.max(1,page-1))} disabled={page<=1} className="p-3 rounded-xl bg-white/10 disabled:opacity-30" aria-label="Página anterior"><ChevronLeft/></button><span className="text-sm text-white/55">Página {page} de {song.pages||1}</span><button onClick={()=>setPage(Math.min(song.pages||1,page+1))} disabled={page>=(song.pages||1)} className="p-3 rounded-xl bg-white/10 disabled:opacity-30" aria-label="Página siguiente"><ChevronRight/></button></div>{notes&&<NotesPanel song={song} onClose={()=>setNotes(false)}/>}</div>;
}