import React, { useRef, useState } from 'react';
export default function AnnotationLayer({items=[],onChange,tool='lapiz',color='#eebd49',enabled=true}) {
  const ref=useRef(null), [draft,setDraft]=useState(null);
  const point=e=>{const r=ref.current.getBoundingClientRect();return [Math.round((e.clientX-r.left)/r.width*1000),Math.round((e.clientY-r.top)/r.height*1000)]};
  const down=e=>{if(!enabled||tool==='borrador')return; e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId); const p=point(e);if(tool==='texto'){const text=window.prompt('Escribe tu anotación');if(text)onChange([...items,{tool:'texto',points:[p],text,color}]);return}setDraft({tool,points:[p],color})};
  const move=e=>{if(draft){const p=point(e);setDraft(v=>({...v,points:[...v.points,p]}))}};
  const up=()=>{if(draft){const last=draft.points.at(-1),first=draft.points[0];onChange([...items,{...draft,points:draft.points.length===1?[first,[first[0]+1,first[1]+1]]:draft.points}]);setDraft(null)}};
  const render=(item,i)=>{const p=item.points||[]; if(!p.length)return null; const common={stroke:item.color||'#eebd49',strokeWidth:item.tool==='resaltador'?24:4,strokeLinecap:'round',strokeLinejoin:'round',fill:'none',opacity:item.tool==='resaltador'?.4:1};let shape;if(item.tool==='texto')shape=<text x={p[0][0]} y={p[0][1]} fill={item.color} fontSize="35" fontWeight="bold">{item.text}</text>;else if(item.tool==='forma')shape=<rect x={Math.min(p[0][0],p.at(-1)[0])} y={Math.min(p[0][1],p.at(-1)[1])} width={Math.abs(p.at(-1)[0]-p[0][0])} height={Math.abs(p.at(-1)[1]-p[0][1])} {...common}/>;else if(item.tool==='flecha')shape=<><path d={`M ${p[0].join(' ')} L ${p.at(-1).join(' ')}`} {...common}/><circle cx={p.at(-1)[0]} cy={p.at(-1)[1]} r="7" fill={item.color}/></>;else shape=<polyline points={p.map(v=>v.join(',')).join(' ')} {...common}/>;return <g key={i} onClick={e=>{if(tool==='borrador'&&enabled){e.stopPropagation();onChange(items.filter((_,n)=>n!==i))}}} className={tool==='borrador'?'cursor-pointer':''}>{shape}</g>};
  return <svg ref={ref} viewBox="0 0 1000 1300" preserveAspectRatio="none" className={`absolute inset-0 w-full h-full z-10 ${enabled?'touch-none cursor-crosshair':'pointer-events-none'}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{items.map(render)}{draft&&render(draft,'draft')}</svg>;
}