import React, { useState } from 'react';
import { X, Upload, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useStage } from './StageProvider';
export default function ImportDialog({onClose, initialFile}) {
  const {saveSong} = useStage();
  const [form,setForm] = useState({title:'',artist:'',key:'',bpm:'',type:'Partitura',folder:'Sin carpeta',tags:''});
  const [file,setFile] = useState(initialFile || null), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { let file_url=''; if(file) { const result = await base44.integrations.Core.UploadPublicFile({file}); file_url=result.file_url; } const saved = await saveSong({...form,bpm:Number(form.bpm)||0,file_url,pages:1,duration:180}); onClose(saved); } catch(e) { setError(e.message || 'No se pudo importar la partitura.'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="bg-[#292d36] text-white rounded-3xl w-full max-w-lg p-6 sm:p-8 shadow-2xl max-h-[90vh] overflow-y-auto"><div className="flex justify-between items-center mb-6"><div><div className="text-xs text-[#c9ef72] uppercase tracking-widest font-bold">BIBLIOTECA</div><h2 className="text-2xl font-bold mt-1">Importar partitura</h2></div><button onClick={onClose} aria-label="Cerrar" className="p-2 rounded-xl hover:bg-white/10"><X/></button></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm text-white/60">Título *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Nombre de la canción" className="stage-input mt-2"/></label><label className="block text-sm text-white/60">Artista o compositor<input value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})} placeholder="¿De quién es?" className="stage-input mt-2"/></label><div className="grid grid-cols-2 gap-4"><label className="text-sm text-white/60">Tonalidad<input value={form.key} onChange={e=>setForm({...form,key:e.target.value})} placeholder="Ej. Sol" className="stage-input mt-2"/></label><label className="text-sm text-white/60">BPM<input type="number" min="1" value={form.bpm} onChange={e=>setForm({...form,bpm:e.target.value})} placeholder="Ej. 120" className="stage-input mt-2"/></label></div><div className="grid grid-cols-2 gap-4"><label className="text-sm text-white/60">Carpeta<input value={form.folder} onChange={e=>setForm({...form,folder:e.target.value})} className="stage-input mt-2"/></label><label className="text-sm text-white/60">Etiquetas<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="Pop, Acústico" className="stage-input mt-2"/></label></div><label className="flex flex-col items-center gap-2 border border-dashed border-white/25 rounded-2xl p-6 text-center cursor-pointer hover:border-[#c9ef72] transition-colors"><Upload size={24} className="text-[#c9ef72]"/><span className="text-sm font-medium">{file?file.name:'Seleccionar PDF o imagen'}</span><span className="text-xs text-white/40">Opcional · También puedes crear un chart sin archivo</span><input type="file" accept=".pdf,image/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{error&&<p role="alert" className="text-red-300 text-sm">{error}</p>}<button disabled={busy} className="w-full h-12 rounded-xl bg-[#c9ef72] text-[#182017] font-bold flex items-center justify-center gap-2">{busy?<><Loader2 className="animate-spin" size={18}/> Importando...</>:'Guardar en biblioteca'}</button></form></div></div>;
}