import React, { useState } from 'react';
import { DragDropContext, Droppable, Draggable } from '@hello-pangea/dnd';
import { GripVertical, Plus, X, Play, Clock3, CalendarDays, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useStage } from './StageProvider';
export default function SetEditor({setlist}) {
  const {songs,saveSet} = useStage(); const [adding,setAdding] = useState(false); const [busy,setBusy] = useState(false);
  const ids = setlist.song_ids||[]; const ordered=ids.map(id=>songs.find(s=>s.id===id)).filter(Boolean);
  const minutes=Math.round(ordered.reduce((total,s)=>total+(s.duration||180),0)/60);
  const change = async next => {setBusy(true); try {await saveSet({song_ids:next},setlist.id);} finally {setBusy(false);} };
  const drop = result => { if(!result.destination||result.destination.index===result.source.index)return; const next=[...ids]; const [item]=next.splice(result.source.index,1); next.splice(result.destination.index,0,item); change(next); };
  return <div className="space-y-5"><div className="flex flex-wrap items-center gap-3 text-sm text-white/50"><span className="flex items-center gap-2"><CalendarDays size={16}/>{setlist.date?new Date(setlist.date+'T12:00:00').toLocaleDateString('es',{day:'numeric',month:'long',year:'numeric'}):'Sin fecha'}</span><span>·</span><span>{setlist.venue||'Lugar por definir'}</span><span>·</span><span className="flex items-center gap-1"><Clock3 size={16}/>{minutes} min</span></div><div className="flex flex-wrap gap-3"><Link to={`/presentacion/${setlist.id}`} className="h-11 px-5 bg-[#c9ef72] text-[#172013] font-bold rounded-xl flex items-center gap-2 text-sm"><Play size={17} fill="currentColor"/> Comenzar presentación</Link><Link to={`/modo-banda/${setlist.id}`} className="h-11 px-4 bg-white/10 text-white rounded-xl flex items-center gap-2 text-sm"><Users size={17}/> Modo banda</Link></div><div className="flex items-center justify-between pt-3"><div><h3 className="font-bold text-lg">Orden de canciones</h3><p className="text-sm text-white/40">Arrastra para cambiar el orden del show.</p></div><button onClick={()=>setAdding(!adding)} className="text-[#c9ef72] text-sm flex items-center gap-1 font-semibold"><Plus size={17}/> Agregar</button></div>{adding&&<div className="bg-[#292d36] p-4 rounded-2xl space-y-2"><div className="flex justify-between text-sm mb-3"><strong>Agregar desde biblioteca</strong><button onClick={()=>setAdding(false)} aria-label="Cerrar"><X size={18}/></button></div>{songs.filter(s=>!ids.includes(s.id)).map(s=><button key={s.id} onClick={()=>{change([...ids,s.id]);setAdding(false)}} className="flex justify-between w-full p-3 bg-white/5 rounded-xl text-sm hover:bg-white/10 text-left">{s.title}<Plus size={16}/></button>)}{songs.every(s=>ids.includes(s.id))&&<p className="text-sm text-white/40">Todas tus canciones ya están en este repertorio.</p>}</div>}
    <DragDropContext onDragEnd={drop}><Droppable droppableId="set-songs">{provided=><div {...provided.droppableProps} ref={provided.innerRef} className="space-y-2">{ordered.map((s,i)=><Draggable key={s.id} draggableId={s.id} index={i} isDragDisabled={busy}>{provided=><div ref={provided.innerRef} {...provided.draggableProps} className="flex items-center gap-3 bg-[#292d36] rounded-xl p-3 border border-white/[.06]"><span {...provided.dragHandleProps} aria-label={`Mover ${s.title}`} className="text-white/35 p-1 cursor-grab"><GripVertical size={19}/></span><span className="text-sm text-white/30 w-5">{String(i+1).padStart(2,'0')}</span><div className="flex-1 min-w-0"><div className="font-semibold text-sm truncate">{s.title}</div><div className="text-xs text-white/40">{s.key||'—'} · {s.bpm||'—'} BPM · {Math.round((s.duration||180)/60)} min</div></div><button onClick={()=>change(ids.filter(id=>id!==s.id))} aria-label={`Quitar ${s.title}`} className="p-2 text-white/35 hover:text-red-300"><X size={17}/></button></div>}</Draggable>)}{provided.placeholder}</div>}</Droppable></DragDropContext>{!ordered.length&&<div className="text-sm text-white/45 p-8 border border-dashed border-white/15 rounded-xl text-center">Agrega canciones para preparar este show.</div>}</div>;
}